image_parameters:
  height_og: 700
  img_path: ../img/static_frame_from_video.jpg
  p1:
  - 17
  - 468
  p2:
  - 27
  - 63
  p3:
  - 676
  - 465
  p4:
  - 687
  - 72
  size_frame: '700'
  width_og: 525
